use_frameworks!

target 'TinyDropbox_Example' do
  pod 'TinyDropbox', :path => '../'

  target 'TinyDropbox_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
