use_frameworks!

abstract_target 'Pod' do
    
    pod 'TinyDropbox', :path => '../'
    
    target 'TinyDropbox_Example' do
        platform :ios, '10.0'
#        target 'TBDropboxKit_Tests' do
#            inherit! :search_paths
#        end
    end
end
