use_frameworks!

target 'TinyDropbox_Example' do
  pod 'TinyDropbox', :path => '../'
  pod 'TBDropboxKit'
  pod 'BuchaSwift'
# pod 'TBDropboxKit', :path=> '~/repos/,github/TBDropboxKit'
# pod 'TBLogger', :path=> '~/repos/,github/TBLogger'

end
